/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import User.Users;
import static java.time.Clock.system;
import java.util.*;
import javax.swing.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.plaf.synth.Region;
import sql.SQL;

/**
 *
 * @author aaawa
 */
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */
    public UserProfile(String userid, Users displayed) {
        initComponents();
        jLabel_username.setText(userid);
        String Name = SQL.user.GetName(userid);
        jLabel_name.setText(Name);
        
        jLabel_Username.setText(displayed.Username);
        jLabel_Name.setText(displayed.Name);
        List<Users> list=SQL.user.GetFollowers(displayed.Username);
        jLabel_Followers.setText(String.valueOf(list.size()) + "  Followers");
        List<Users> list2 = SQL.user.GetFollowing(displayed.Username);
        jLabel_Following.setText(String.valueOf(list2.size()) + "  Following");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel_Home11 = new javax.swing.JLabel();
        jLabel_Bookmarks11 = new javax.swing.JLabel();
        jLabel_Profile11 = new javax.swing.JLabel();
        jButton_Tweet11 = new javax.swing.JButton();
        jLabel_name = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jLabel_Followers = new javax.swing.JLabel();
        jLabel_Following = new javax.swing.JLabel();
        jButton_Message = new javax.swing.JButton();
        jButton_Tweets = new javax.swing.JButton();
        jButton_Likes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton_Search = new javax.swing.JButton();
        jButton_Follow = new javax.swing.JButton();
        jButton_Block = new javax.swing.JButton();
        jButton_UnFollow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel_Home11.setBackground(new java.awt.Color(51, 255, 255));
        jLabel_Home11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Home11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons/WhatsApp Image 2020-11-07 at 11.11.26 PM.jpeg"))); // NOI18N
        jLabel_Home11.setText("Home");
        jLabel_Home11.setAlignmentX(0.5F);
        jLabel_Home11.setFocusable(false);
        jLabel_Home11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel_Home11.setIconTextGap(30);
        jLabel_Home11.setMaximumSize(new java.awt.Dimension(100, 128));
        jLabel_Home11.setMinimumSize(new java.awt.Dimension(100, 128));
        jLabel_Home11.setPreferredSize(new java.awt.Dimension(100, 128));
        jLabel_Home11.setRequestFocusEnabled(false);
        jLabel_Home11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Home11MouseClicked(evt);
            }
        });

        jLabel_Bookmarks11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Bookmarks11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons/bookmark.png"))); // NOI18N
        jLabel_Bookmarks11.setText("Bookmarks");
        jLabel_Bookmarks11.setIconTextGap(30);
        jLabel_Bookmarks11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Bookmarks11MouseClicked(evt);
            }
        });

        jLabel_Profile11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Profile11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons/Home.jpeg"))); // NOI18N
        jLabel_Profile11.setText("Profile");
        jLabel_Profile11.setIconTextGap(30);
        jLabel_Profile11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Profile11MouseClicked(evt);
            }
        });

        jButton_Tweet11.setBackground(new java.awt.Color(25, 181, 254));
        jButton_Tweet11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Tweet11.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Tweet11.setText("Tweet");
        jButton_Tweet11.setBorder(null);
        jButton_Tweet11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tweet11ActionPerformed(evt);
            }
        });

        jLabel_name.setBackground(new java.awt.Color(51, 255, 255));
        jLabel_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name.setText("Name");
        jLabel_name.setAlignmentX(0.5F);
        jLabel_name.setFocusable(false);
        jLabel_name.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel_name.setIconTextGap(30);
        jLabel_name.setMaximumSize(new java.awt.Dimension(100, 128));
        jLabel_name.setMinimumSize(new java.awt.Dimension(100, 128));
        jLabel_name.setPreferredSize(new java.awt.Dimension(100, 128));
        jLabel_name.setRequestFocusEnabled(false);

        jLabel_username.setText("@username");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jButton_Tweet11, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_Bookmarks11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(jLabel_Home11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_Profile11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Home11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Bookmarks11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Profile11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButton_Tweet11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel21.setLayout(null);

        jLabel_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Name.setText("Name");
        jPanel21.add(jLabel_Name);
        jLabel_Name.setBounds(20, 20, 190, 40);

        jLabel_Username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Username.setText("Username");
        jPanel21.add(jLabel_Username);
        jLabel_Username.setBounds(20, 60, 190, 13);

        jLabel_Followers.setText("$ Followers");
        jLabel_Followers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_FollowersMouseClicked(evt);
            }
        });
        jPanel21.add(jLabel_Followers);
        jLabel_Followers.setBounds(520, 80, 130, 30);

        jLabel_Following.setText("$ Following");
        jLabel_Following.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_FollowingMouseClicked(evt);
            }
        });
        jPanel21.add(jLabel_Following);
        jLabel_Following.setBounds(370, 80, 130, 30);

        jButton_Message.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Message.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Message.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Message.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/iconfinder_Mail_613533 (1).png"))); // NOI18N
        jButton_Message.setBorder(null);
        jButton_Message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MessageActionPerformed(evt);
            }
        });
        jPanel21.add(jButton_Message);
        jButton_Message.setBounds(580, 20, 60, 50);

        jButton_Tweets.setBackground(new java.awt.Color(25, 181, 254));
        jButton_Tweets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Tweets.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Tweets.setText("Tweets");
        jButton_Tweets.setBorder(null);
        jButton_Tweets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TweetsActionPerformed(evt);
            }
        });

        jButton_Likes.setBackground(new java.awt.Color(25, 181, 254));
        jButton_Likes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Likes.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Likes.setText("Likes");
        jButton_Likes.setBorder(null);
        jButton_Likes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LikesActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("Enter Text...");

        jButton_Search.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Search.setForeground(new java.awt.Color(25, 181, 254));
        jButton_Search.setText("Search");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton_Follow.setBackground(new java.awt.Color(25, 181, 254));
        jButton_Follow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Follow.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Follow.setText("Follow");
        jButton_Follow.setBorder(null);
        jButton_Follow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FollowActionPerformed(evt);
            }
        });

        jButton_Block.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Block.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Block.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Block.setText("Block");
        jButton_Block.setBorder(null);
        jButton_Block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BlockActionPerformed(evt);
            }
        });

        jButton_UnFollow.setBackground(new java.awt.Color(255, 51, 0));
        jButton_UnFollow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_UnFollow.setForeground(new java.awt.Color(255, 255, 255));
        jButton_UnFollow.setText("Unfollow");
        jButton_UnFollow.setBorder(null);
        jButton_UnFollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UnFollowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton_UnFollow, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(jButton_Block, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton_Tweets, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                                            .addComponent(jButton_Likes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Follow, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Tweets, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Likes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Follow, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_UnFollow, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Block, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_Home11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Home11MouseClicked
        // TODO add your handling code here:
        String userid = jLabel_username.getText();
        
        Home p = new Home(userid);
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //p.setDefaultCloseOperation(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jLabel_Home11MouseClicked

    private void jLabel_Bookmarks11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Bookmarks11MouseClicked
        // TODO add your handling code here:
        String userid = jLabel_username.getText();
        
        Bookmarks bm = new Bookmarks(userid);
        bm.setVisible(true);
        bm.pack();
        bm.setLocationRelativeTo(null);
        bm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //bm.setDefaultCloseOperation(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jLabel_Bookmarks11MouseClicked

    private void jLabel_Profile11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Profile11MouseClicked
        // TODO add your handling code here:
        String userid = jLabel_username.getText();
        
        Profile p = new Profile(userid);
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //p.setDefaultCloseOperation(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jLabel_Profile11MouseClicked

    private void jButton_Tweet11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tweet11ActionPerformed
        // TODO add your handling code here:
        String userid = jLabel_username.getText();
        
        Tweet t= new Tweet(userid);
        t.setVisible(true);
        t.pack();
        t.setLocationRelativeTo(null);
        t.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //this.dispose();
    }//GEN-LAST:event_jButton_Tweet11ActionPerformed

    private void jButton_TweetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TweetsActionPerformed
        // TODO add your handling code here
        String userid = jLabel_username.getText();
        String display = jLabel_Username.getText();
        String type = "Tweets";
        
        TweetPage tp = new TweetPage(userid,display,type);
        tp.setVisible(true);
        tp.pack();
        tp.setLocationRelativeTo(null);
        tp.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //tp.setDefaultCloseOperation(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButton_TweetsActionPerformed

    private void jButton_LikesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LikesActionPerformed
        // TODO add your handling code here:
        String userid = jLabel_username.getText();
        String display = jLabel_Username.getText();
        String type = "Likes";
        
        TweetPage tp = new TweetPage(userid,display,type);
        tp.setVisible(true);
        tp.pack();
        tp.setLocationRelativeTo(null);
        tp.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //tp.setDefaultCloseOperation(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButton_LikesActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // TODO add your handling code here:
        String text = jTextField1.getText();
        String userid = jLabel_username.getText();
        
        List<Users> users= SQL.user.Search(text);
        
        SearchedUserlist p = new SearchedUserlist(userid,text,users);
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //p.setDefaultCloseOperation(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jButton_FollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FollowActionPerformed
        // TODO add your handling code here:
        String c_user_id = jLabel_username.getText();
        String username = jLabel_Username.getText();
        
        int result = SQL.user.Follow(c_user_id, username);
        if(result == 1){
            JOptionPane.showMessageDialog(rootPane, "Followed Successfully.!!!");
        }
        else if(result == 0){
            JOptionPane.showMessageDialog(rootPane, "Can't Follow," + jLabel_Name.getText() + "has blocked you.!!!");
        }
        else if(result == -1){
            JOptionPane.showMessageDialog(rootPane, "Can't Follow, You have blocked" + jLabel_Name.getText() +".!!!");
        }
        else if(result == -2){
            JOptionPane.showMessageDialog(rootPane, "Already Following.!!!");
        }
    }//GEN-LAST:event_jButton_FollowActionPerformed

    private void jButton_BlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BlockActionPerformed
        // TODO add your handling code here:
        String c_user_id = jLabel_username.getText();
        String username = jLabel_Username.getText();
        
        int result = SQL.user.Block(c_user_id, username);
        if(result == 1){
            JOptionPane.showMessageDialog(rootPane, "Blocked Successfully.!!!");
        }
        else if(result == -1){
            JOptionPane.showMessageDialog(rootPane, "Already Blocked. Unblocking " + jLabel_Name.getText() + ".!!!");
        }
    }//GEN-LAST:event_jButton_BlockActionPerformed

    private void jButton_UnFollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UnFollowActionPerformed
        // TODO add your handling code here:
        String c_user_id = jLabel_username.getText();
        String username = jLabel_Username.getText();
        
        int result = SQL.user.UnFollow(c_user_id, username);
        if(result == 1){
            JOptionPane.showMessageDialog(rootPane, "UnFollowed Successfully.!!!");
        }
        else if(result == 0){
            JOptionPane.showMessageDialog(rootPane, "Can't UnFollow. You are not following " + jLabel_Name.getText() + ".!!!");
        }
    }//GEN-LAST:event_jButton_UnFollowActionPerformed

    private void jLabel_FollowingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_FollowingMouseClicked
        // TODO add your handling code here:
        String userid = jLabel_Username.getText();
        
        List<Users> users= SQL.user.GetFollowing(userid);
        
        UserList p = new UserList(userid,users);
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //p.setDefaultCloseOperation(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jLabel_FollowingMouseClicked

    private void jLabel_FollowersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_FollowersMouseClicked
        // TODO add your handling code here:
        String userid = jLabel_Username.getText();
        
        List<Users> users= SQL.user.GetFollowers(userid);
        
        UserList p = new UserList(userid,users);
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //p.setDefaultCloseOperation(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jLabel_FollowersMouseClicked

    private void jButton_MessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MessageActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_MessageActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Block;
    private javax.swing.JButton jButton_Follow;
    private javax.swing.JButton jButton_Likes;
    private javax.swing.JButton jButton_Message;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Tweet11;
    private javax.swing.JButton jButton_Tweets;
    private javax.swing.JButton jButton_UnFollow;
    private javax.swing.JLabel jLabel_Bookmarks11;
    private javax.swing.JLabel jLabel_Followers;
    private javax.swing.JLabel jLabel_Following;
    private javax.swing.JLabel jLabel_Home11;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Profile11;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
